In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as stm

In [3]:
df = pd.read_csv('Data/House_Price.csv')
df.head()

,price,crime_rate,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,airport,n_hos_beds,n_hot_rooms,waterbody,rainfall,bus_ter,parks
0,24.0,0.00632,32.31,0.538,6.575,65.2,4.35,3.81,4.18,4.01,24.7,4.98,YES,5.480,11.1920,River,23,YES,0.049347
1,21.6,0.02731,37.07,0.469,6.421,78.9,4.99,4.70,5.12,5.06,22.2,9.14,NO,7.332,12.1728,Lake,42,YES,0.046146
2,34.7,0.02729,37.07,0.469,7.185,61.1,5.03,4.86,5.01,4.97,22.2,4.03,NO,7.394,101.1200,None,38,YES,0.045764
3,33.4,0.03237,32.18,0.458,6.998,45.8,6.21,5.93,6.16,5.96,21.3,2.94,YES,9.268,11.2672,Lake,45,YES,0.047151
4,36.2,0.06905,32.18,0.458,7.147,54.2,6.16,5.86,6.37,5.86,21.3,5.33,NO,8.824,11.2896,Lake,55,YES,0.039474

In [4]:
df.isnull().sum()

price          0
crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [5]:
df['n_hos_beds'] = df['n_hos_beds'].fillna(df['n_hos_beds'].mean())

In [6]:
df.isnull().sum()

price          0
crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     0
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [7]:
df.corr()

,price,crime_rate,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks
price,1.000000,-0.389582,-0.484754,-0.429300,0.696304,-0.377999,0.251355,0.249459,0.246650,0.248200,0.505655,-0.740836,0.108880,0.023122,-0.047426,-0.391574
crime_rate,-0.389582,1.000000,0.406583,0.420972,-0.219247,0.352734,-0.380050,-0.379813,-0.380069,-0.376462,-0.289946,0.455621,0.017371,0.013518,0.059204,0.383235
resid_area,-0.484754,0.406583,1.000000,0.763651,-0.391676,0.644779,-0.706481,-0.707956,-0.707566,-0.705819,-0.383248,0.603800,0.005799,-0.000839,0.055810,0.707635
air_qual,-0.429300,0.420972,0.763651,1.000000,-0.302188,0.731470,-0.768589,-0.769724,-0.769157,-0.764873,-0.188933,0.590879,-0.049553,-0.004882,0.092104,0.915544
room_num,0.696304,-0.219247,-0.391676,-0.302188,1.000000,-0.240265,0.208464,0.203981,0.201907,0.205397,0.355501,-0.613808,0.032009,0.030674,-0.064694,-0.282817
age,-0.377999,0.352734,0.644779,0.731470,-0.240265,1.000000,-0.746904,-0.746493,-0.747021,-0.746707,-0.261515,0.602339,-0.021012,0.009380,0.075198,0.673850
dist1,0.251355,-0.380050,-0.706481,-0.768589,0.208464,-0.746904,1.000000,0.997905,0.997735,0.994073,0.232834,-0.498823,-0.030365,-0.014463,-0.036794,-0.706319
dist2,0.249459,-0.379813,-0.707956,-0.769724,0.203981,-0.746493,0.997905,1.000000,0.998097,0.994003,0.233707,-0.495693,-0.031071,-0.010239,-0.038005,-0.708237
dist3,0.246650,-0.380069,-0.707566,-0.769157,0.201907,-0.747021,0.997735,0.998097,1.000000,0.994126,0.233588,-0.494290,-0.028315,-0.010077,-0.041470,-0.709346
dist4,0.248200,-0.376462,-0.705819,-0.764873,0.205397,-0.746707,0.994073,0.994003,0.994126,1.000000,0.228256,-0.496084,-0.021534,-0.005850,-0.032542,-0.703508
teachers,0.505655,-0.289946,-0.383248,-0.188933,0.355501,-0.261515,0.232834,0.233707,0.233588,0.228256,1.000000,-0.374044,-0.008056,-0.023343,-0.045836,-0.187004
poor_prop,-0.740836,0.455621,0.603800,0.590879,-0.613808,0.602339,-0.498823,-0.495693,-0.494290,-0.496084,-0.374044,1.000000,-0.066008,0.003337,0.061581,0.552310
n_hos_beds,0.108880,0.017371,0.005799,-0.049553,0.032009,-0.021012,-0.030365,-0.031071,-0.028315,-0.021534,-0.008056,-0.066008,1.000000,-0.005455,0.058628,-0.071272
n_hot_rooms,0.023122,0.013518,-0.000839,-0.004882,0.030674,0.009380,-0.014463,-0.010239,-0.010077,-0.005850,-0.023343,0.003337,-0.005455,1.000000,-0.004840,0.006262
rainfall,-0.047426,0.059204,0.055810,0.092104,-0.064694,0.075198,-0.036794,-0.038005,-0.041470,-0.032542,-0.045836,0.061581,0.058628,-0.004840,1.000000,0.078641
parks,-0.391574,0.383235,0.707635,0.915544,-0.282817,0.673850,-0.706319,-0.708237,-0.709346,-0.703508,-0.187004,0.552310,-0.071272,0.006262,0.078641,1.000000

In [8]:
x = df['room_num']
y = df['price']

In [9]:
# Define Slope

slope = ((x-x.mean())*(y-y.mean())).sum()/(np.square(x-x.mean())).sum()
slope

9.099669663064661

In [10]:
# Define Intercept

intercept = y.mean() - (slope*x.mean())
intercept

-34.65924312309723

In [11]:
# Define Residual sum of squares (RSS) as part of RSE formula

rss = (np.square(y-intercept-(slope*x))).sum()
rss

21934.391586319405

In [12]:
# Define Residual Standard Error (RSE)

rse = np.sqrt(rss/(len(x)-2))
rse

6.597015857705984

In [13]:
# Define R-Square

tss = np.square(y-y.mean()).sum() # Total Sum of Squares
r2 = 1 - (rss/tss)
r2

0.48483897365368667

In [14]:
# Define model prediction using model y = mx + b
# m = slope
# x = data point (independent variable)
# b = intercept

y_pred = ((slope*x)+intercept)
y_pred

0      25.171085
1      23.769736
2      30.721883
3      29.020245
4      30.376096
         ...
501    25.334879
502    21.030735
503    28.820052
504    27.163913
505    20.211765
Name: room_num, Length: 506, dtype: float64

In [24]:
# OLS using statsmodels

X = stm.add_constant(df['room_num'])
y = df['price']

model_ols = stm.OLS(y, X)
result = model_ols.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.485
Model:                            OLS   Adj. R-squared:                  0.484
Method:                 Least Squares   F-statistic:                     474.3
Date:                Mon, 07 Dec 2020   Prob (F-statistic):           1.31e-74
Time:                        16:23:12   Log-Likelihood:                -1671.6
No. Observations:                 506   AIC:                             3347.
Df Residuals:                     504   BIC:                             3356.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -34.6592      2.642    -13.118      0.000     -39.850     -29.468
room_num       9.0997      0.418     21.779      0.000       8.279       9.921
==============================================================================
Omnibus:                      103.753   Durbin-Watson:                   0.681
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              633.429
Skew:                           0.729   Prob(JB):                    2.84e-138
Kurtosis:                       8.284   Cond. No.                         58.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
print('Parameters: ', result.params)
print('\n')
print('Standard Error: ', result.bse)
print('\n')
print('r2: ', result.rsquared)
print('\n')
print('Predicted Value: ', result.predict())

Parameters:  const      -34.659243
room_num     9.099670
dtype: float64


Standard Error:  const       2.642136
room_num    0.417814
dtype: float64


r2:  0.4848389736536869


Predicted Value:  [25.17108491 23.76973578 30.72188341 29.02024518 30.37609596 23.85163281
 20.04797089 21.50391804 16.58099675 19.97517353 23.36935032 20.02067188
 18.92871152 19.4746917  20.81234314 18.42822969 19.34729633 19.84777816
 14.98855456 17.45456504 16.0259169  19.62028642 21.23092795 18.23713663
 19.24719996 16.28980732 18.23713663 20.36645933 24.44311134 26.07195221
 17.32716966 20.59395107 19.48379137 17.21797363 20.81234314 19.32909699
 18.49192738 18.57382441 19.62938609 25.3530783  29.25683659 26.9455205
 21.47661903 21.85880515 20.56665206 17.0450799  17.99144555 20.21176495
 14.46987339 16.31710633 19.60208708 20.98523687 24.58870605 19.92057552
 18.91961185 31.30426226 23.42394834 27.3641053  21.25822696 19.27449897
 17.58196041 19.62938609 24.08822422 26.87272314 29.98481016 22.57767906
 18.00054522 18.82861516 16.24430897 18.89231284 23.7333371  19.58388774
 20.53025338 22.16819392 22.42298467 22.54128038 22.47758269 21.21272861
 22.04989822 18.79221648 26.5542347  25.57147038 22.68687509 21.45841969
 23.47854635 25.67156674 20.0752699  21.03983488 29.10214221 29.75731842
 23.7333371  23.62414107 23.96082885 21.85880515 22.2045926  25.62606839
 21.42202101 38.76599139 36.50017364 32.8239071  26.5542347  27.04561686
 23.62414107 21.1854296  21.45841969 18.58292408 18.44642903 21.0944329
 24.25201828 22.02259921 21.71321044 26.44503866 19.14710359 20.77594446
 22.25009095 19.28359864 21.54031672 20.12986792 18.77401714 17.49096372
 18.7558178  19.97517353 19.58388774 18.62842242 18.83771483 19.81137948
 16.4172027  17.14517627 23.86073248 16.63559477 24.10642356 22.90526717
 23.32385197 18.31903366 17.72755513 22.98716419 19.41099401 24.07002488
 18.63752209 21.31282497 21.52211738 11.01199892 14.50627207 15.09775059
  9.95643723 21.12173191 16.55369774 10.16572964 12.53164375 16.27160798
 21.04893455 14.51537174 10.94830123 17.29077098 21.11263224 21.32192464
 13.31421534 28.51976335 20.53935305 24.57960638 22.21369227 33.48818298
 36.33637959 41.55049031 18.61022308 20.85784149 37.49203764 18.81951549
 22.84156948 23.59684206 18.80131615 18.8468145  16.04411624 23.72423744
 18.65572143 24.90719449 20.12076825 22.8051708  27.76449077 28.85645113
 35.99969181 21.24912729 30.44889332 25.06188888 16.33530567 21.33102431
 36.60027001 27.05471653 24.99819119 30.72188341 28.5925607  26.66343074
 30.65818572 27.21851059 25.43497533 37.00065547 31.65004971 30.01210917
 31.53175401 28.81095278 30.26689992 21.41292134 34.58924301 36.80046274
 38.44750295 18.94691086 22.90526717 17.96414654 20.52115371 13.96939156
 19.57478807 14.51537174 18.18253861 23.35115098 14.58816909 21.59491473
 18.91961185 25.78076278 19.49289104 23.33295164 28.5925607  21.43112068
 27.93738449 25.56237071 40.55862631 44.73537469 38.50210097 30.52169067
 35.28081791 24.96179251 19.76588113 32.78750842 41.20470286 40.38573259
 26.54513503 20.72134645 25.68066641 32.29612626 24.31571596 25.45317467
 28.10117854 20.80324347 23.19645659 23.51494503 16.2352093  16.34440534
 20.92153918 21.9953002  23.87893182 26.47233767 24.37031398 23.92443017
 28.64715872 40.49492862 20.92153918 18.81041582 33.16969455 44.54428162
 32.06863452 27.60069671 30.88567746 33.77027274 41.75978271 32.0140365
 30.91297647 15.9349202  29.16583989 40.84071607 33.31528926 19.21080128
 18.62842242 22.12269557 24.83439713 35.32631626 26.83632446 27.70989275
 31.46805632 27.455102   24.32481563 27.32770662 36.50017364 28.74725509
 34.90773145 37.43743962 29.83921545 24.06092521 22.03169888 21.84060581
 22.8051708  25.08008821 27.77359044 30.38519563 25.67156674 21.0944329
 20.02067188 26.10835089 24.9344935  18.02784423 23.07816089 29.41153097
 27.86458713 25.30757996 24.44311134 28.87465046 31.18596656 25.54417137
 32.86030578 27.6643944  25.71706509 19.6839841  10.59341411 21.04893455
 20.14806726 22.35928699 25.09828755 17.2543723  19.15620326 17.95504687
 23.41484867 20.96703753 23.81523413 23.36025065 20.31186131 17.28167131
 23.71513777 23.86073248 22.77787179 20.69404744 18.73761846 22.96896485
 21.24912729 17.26347197 20.22086461 22.81427047 22.75967245 20.27546263
 18.74671813 18.98330954 20.47565537 19.80227981 19.64758543 31.23146491
 24.85259647 26.27214494 27.89188614 20.06617023 19.01060855 24.6342044
 25.71706509 28.48336467 24.39761299 25.20748359 18.88321317 26.56333437
 16.87218618 19.356396   21.86790482 23.53314437 21.0944329  20.95793786
 23.56044338 22.22279194 14.13318561 18.14613993 45.23585652 -2.25531945
 10.50241741  0.49278079 10.5661151  26.15384924 29.18403923 21.9043035
 18.80131615  9.98373624  2.99518994 31.88664112 25.84446047 27.16391257
 23.39664933 21.96800119 28.74725509 24.89809482 15.71652813 15.57093342
  5.08811397 13.35971369  7.67242015 10.83910519  9.74714483 14.38797636
 17.32716966 20.40285801 11.1666933  21.6950111  18.91051218 24.22471927
 23.62414107 17.63655843 14.96125555 18.59202375 19.82047915 23.05996155
 23.6150414  14.0148899  15.67102978 17.05417957  2.99518994 16.37170435
 16.45360137 27.69169341 17.72755513 25.91725782  7.45402808 12.24955399
  6.46216408 23.88803149 27.05471653 13.60540477 19.54748906 27.43690266
 23.67873909 19.99337287 16.73569113 20.87604083 15.98041855 18.99240921
 18.4555287  21.77690813 21.6950111  23.39664933 23.1054599  27.51879968
 23.80613446 23.90623083 21.83150615 25.66246707 24.13372257 21.32192464
 19.34729633 16.54459807 18.28263498 23.63324074 21.93160251 24.35211464
 18.61022308 24.11552323 23.04176221 22.22279194 21.62221374 23.7333371
 26.75442743 25.89905848 22.64137675 32.6146147  26.56333437 24.71610143
 19.72038278 19.356396   22.67777542 20.6758481  26.31764329 23.36025065
 22.82337014 24.60690539 21.84060581 17.74575447 19.50199071 19.96607386
 19.2653993  17.32716966 21.45841969 22.02259921 23.9153305  28.85645113
 14.72466414 21.41292134 24.34301497 13.60540477 21.62221374 22.02259921
 22.14089491 26.7635271  29.59352437 17.77305348 18.76491747 22.77787179
 20.9761372  19.07430624 14.97035522 14.60636843 11.68537447 19.78408047
 19.78408047 17.27257164 19.2653993  16.93588387 14.38797636 18.0642429
 20.11166858 16.01681723 20.18446594 25.33487897 21.03073521 28.82005245
 27.16391257 20.21176495]